# Generated by Django 5.2.16 on 2026-08-26 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(default='MessageSquare', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Interview Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('model_answer', models.TextField(help_text='Reference answer with high-quality structure')),
                ('tips', models.TextField(blank=True, default='', help_text='Strategy and tips for answering')),
                ('key_talking_points', models.JSONField(blank=True, default=list, help_text='Core points/keywords to cover')),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10)),
                ('company_tag', models.CharField(blank=True, default='General', help_text='e.g. Google, Amazon, TCS, Infosys, Microsoft', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interview.interviewcategory')),
            ],
            options={
                'ordering': ['category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InterviewAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.TextField()),
                ('relevance_score', models.FloatField(default=0.0, help_text='0 to 10')),
                ('clarity_score', models.FloatField(default=0.0, help_text='0 to 10')),
                ('technical_score', models.FloatField(default=0.0, help_text='0 to 10')),
                ('confidence_score', models.FloatField(default=0.0, help_text='0 to 10')),
                ('overall_score', models.FloatField(default=0.0, help_text='0 to 100')),
                ('feedback', models.JSONField(blank=True, default=dict, help_text='Detailed feedback breakdown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_attempts', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='interview.interviewquestion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
