# Generated by Django 5.2.16 on 2026-08-26 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list, help_text="e.g. ['Arrays', 'Two Pointers', 'Dynamic Programming']")),
                ('description', models.TextField()),
                ('input_format', models.TextField(blank=True, default='')),
                ('output_format', models.TextField(blank=True, default='')),
                ('constraints', models.TextField(blank=True, default='')),
                ('sample_input', models.TextField(blank=True, default='')),
                ('sample_output', models.TextField(blank=True, default='')),
                ('sample_explanation', models.TextField(blank=True, default='')),
                ('starter_code', models.JSONField(blank=True, default=dict, help_text='Dictionary keyed by language (python, javascript, java, cpp)')),
                ('test_cases', models.JSONField(default=list, help_text="List of test case dicts: [{'input': '...', 'output': '...', 'is_hidden': false}]")),
                ('points', models.PositiveIntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['difficulty', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CodingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'Python (3.8.1)'), ('javascript', 'JavaScript (Node.js 12.14.0)'), ('java', 'Java (OpenJDK 13.0.1)'), ('cpp', 'C++ (GCC 9.2.0)')], default='python', max_length=20)),
                ('code', models.TextField()),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('WRONG_ANSWER', 'Wrong Answer'), ('TIME_LIMIT_EXCEEDED', 'Time Limit Exceeded'), ('COMPILATION_ERROR', 'Compilation Error'), ('RUNTIME_ERROR', 'Runtime Error'), ('PENDING', 'Pending'), ('ERROR', 'Error')], default='PENDING', max_length=30)),
                ('passed_test_cases', models.PositiveIntegerField(default=0)),
                ('total_test_cases', models.PositiveIntegerField(default=0)),
                ('execution_time_ms', models.FloatField(default=0.0)),
                ('memory_kb', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('test_case_results', models.JSONField(blank=True, default=list)),
                ('score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='coding.codingproblem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
